# http://docs.travis-ci.com/user/languages/c/

language: c

compiler:
  - clang
  - gcc

before_install:
  # build deps
  - sudo apt-get install libsdl1.2-dev

  # test deps
  - sudo apt-get install libcppunit-dev

install:
  - cmake ./
  - make
  - sudo make install

script:
  - echo hello-duck | duck bin/examples/echo.txt
  - echo hello-gduck | gduck bin/examples/echo.txt
